apiVersion: v1
kind: Service
metadata:
  name: permitio-pdp
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
  ports:
    - name: pdp
      port: {{ .Values.pdp.pdpPort }}
      targetPort: 7000
      protocol: TCP
    - name: opa
      port: {{ .Values.pdp.opaPort }}
      targetPort: 8181
      protocol: TCP
